### PR TITLE
Adding Grid controls

### PR DESCRIPTION
**Pull request by echophon**
Adding per pattern/voice
- Increment/decrement nudging of density & length
- Randomization of pitch across 5 'zones'
- Randomization of Env & LFO params
- Simple visualization of pattern playback

### CODE REVIEW

**Comment by cfdrake** [comment]
Awesome! Appreciate the contribution - will give it a go this weekend.

**Comment by echophon** [comment]
Cool.  I may add a few more ideas I've had since I opened the PR, so no hurry.  Open to suggestions/feedback/other ideas.

**Comment by echophon** [comment]
Swapped a number of the random controls in favor of 'nudging' the synth params up or down.  So you can tap in rhythm changes on 1-4, completely randomize the synth voice with 15, and tweak the synth voice with 5-10.  Also randomly changing the lfoShape on trig which acts like an accent

**Comment by echophon** [comment]
ok, I think I'm done on these changes.  If I have additional, I'll open a new PR

**Review by cfdrake — APPROVED** [review]

**Comment by cfdrake** [comment]
@echophon Sorry for the delay - tested it out and works like a charm! Appreciate the update.

**Pull request merged**
